// <auto-generated />
using InternManager.Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InternManager.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531235959_RestoreSchemaIntegrity")]
    partial class RestoreSchemaIntegrity
    {
    }
}